/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import dao.SanPhamDao;
import helper.MessageDialogHelper;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.table.DefaultTableModel;
import model.SanPham;

/**
 *
 * @author nhokk
 */
public class NhanVien_SanPham extends javax.swing.JPanel {

    /**
     * Creates new form NhanVien_QLHV
     */
    private DefaultTableModel tableModel;
    private NhanVienMainForm parentForm;
    private SanPham sp;

    public NhanVien_SanPham() {
        initComponents();

        initTable();
        loadDataToComboBox();
        loadDataToTable();

    }

    private void initTable() {
        tableModel = new DefaultTableModel();
        tableModel.setColumnIdentifiers(new String[]{"Mã sản phẩm", "Tên sản phẩm", "Loại sản phẩm", "Đơn giá","Số lượng"});
        jTable2.setModel(tableModel);
    }

    private void loadDataToTable() {
        try {
            SanPhamDao dao = new SanPhamDao();
            List<SanPham> list = dao.findAll();
            tableModel.setRowCount(0);
            for (SanPham it : list) {
                tableModel.addRow(new Object[]{
                    it.getMaSP(), it.getTen(), it.getLoaiSanPham(), it.getDonGia(), it.getSoLuong()
                });
                tableModel.fireTableDataChanged();
            }
        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(parentForm, e.getMessage(), "Loi");
        }
    }

    private void loadDataToComboBox() {
        try {
            SanPhamDao dao = new SanPhamDao();
            List<String> list = dao.findLoaiSP();
            tableModel.setRowCount(0);
            for (String it : list) {
                cbbLoaiSP.addItem(it);
            }
        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(parentForm, e.getMessage(), "Loi");
        }
    }

    private void loadDataToTable1(String loaisanpham) {
        try {
            SanPhamDao dao = new SanPhamDao();
            List<SanPham> list = dao.findByLoaiSP(loaisanpham);
            tableModel.setRowCount(0);
            for (SanPham it : list) {
                tableModel.addRow(new Object[]{
                    it.getMaSP(), it.getTen(), it.getLoaiSanPham(), it.getDonGia(), it.getSoLuong()
                });
                tableModel.fireTableDataChanged();
            }
        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(parentForm, e.getMessage(), "Loi");
        }
    }
    
    private void loadDataToTable2(String tensanpham) {
        try {
            SanPhamDao dao = new SanPhamDao();
            List<SanPham> list = dao.findByTenSP(tensanpham);
            tableModel.setRowCount(0);
            for (SanPham it : list) {
                tableModel.addRow(new Object[]{
                    it.getMaSP(), it.getTen(), it.getLoaiSanPham(), it.getDonGia(), it.getSoLuong()
                });
                tableModel.fireTableDataChanged();
            }
        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(parentForm, e.getMessage(), "Loi");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnSua = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        Filter1 = new javax.swing.JRadioButton();
        Filter2 = new javax.swing.JRadioButton();
        txtTenSP = new javax.swing.JTextField();
        cbbLoaiSP = new javax.swing.JComboBox<>();
        Filter = new javax.swing.JRadioButton();
        JScrollpane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1280, 700));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSua.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Actions-document-edit-icon-16.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.setBorder(null);
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnThem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Sign_Add_Icon_16.png"))); // NOI18N
        btnThem.setText("Thêm sản phẩm");
        btnThem.setBorder(null);
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnRefresh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Refresh-icon (1).png"))); // NOI18N
        btnRefresh.setText("Cập nhật");
        btnRefresh.setBorder(null);
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Actions-edit-delete-icon-16.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.setBorder(null);
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(300, Short.MAX_VALUE)
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(416, 416, 416)
                .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnThem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 30));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        Filter1.setText("Tìm kiếm theo tên sản phẩm");
        Filter1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Filter1ActionPerformed(evt);
            }
        });

        Filter2.setText("Tìm kiếm theo loại sản phẩm");
        Filter2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Filter2ActionPerformed(evt);
            }
        });

        txtTenSP.setEnabled(false);
        txtTenSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenSPActionPerformed(evt);
            }
        });

        cbbLoaiSP.setEnabled(false);
        cbbLoaiSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbLoaiSPActionPerformed(evt);
            }
        });

        Filter.setSelected(true);
        Filter.setText("Tìm kiếm tất cả sản phẩm");
        Filter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FilterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTenSP, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbbLoaiSP, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Filter2)
                            .addComponent(Filter1)
                            .addComponent(Filter))
                        .addGap(0, 112, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(Filter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Filter1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Filter2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbbLoaiSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(506, Short.MAX_VALUE))
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 300, 670));

        JScrollpane1.setBackground(new java.awt.Color(255, 255, 255));
        JScrollpane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JScrollpane1MouseClicked(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A"},
                {"N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A"},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Tai Khoan", "Ho va ten", "Gioi Tinh", "Ngay Sinh", "Dia Chi", "Email", "SDT", "Trinh Do"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        }
    );
    jTable2.setGridColor(new java.awt.Color(0, 0, 0));
    jTable2.setRowHeight(30);
    jTable2.setShowGrid(true);
    jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jTable2MouseClicked(evt);
        }
    });
    JScrollpane1.setViewportView(jTable2);

    add(JScrollpane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 980, 670));
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        ThemSanPham themSP = new ThemSanPham();
        themSP.setVisible(true);
        themSP.setLocationRelativeTo(null);    
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        XoaSanPham XoaSP = new XoaSanPham(sp);
        XoaSP.setVisible(true);
        XoaSP.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        SuaSanPham SuaSP = new SuaSanPham(sp);
        SuaSP.setVisible(true);
        SuaSP.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        Filter1.setSelected(false);
        Filter2.setSelected(false);
        txtTenSP.setEnabled(false);
        txtTenSP.setText("");
        cbbLoaiSP.setEnabled(false);
        if (Filter.getVerifyInputWhenFocusTarget() == true) {
            Filter.setSelected(true);
        }
        loadDataToTable();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void JScrollpane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JScrollpane1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_JScrollpane1MouseClicked

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        try {
            int row = jTable2.getSelectedRow();

            if (row >= 0) {
                String id = (String) jTable2.getValueAt(row, 0);
                SanPhamDao dao = new SanPhamDao();
                sp = dao.findById(id);
            }

            if (sp != null) {

            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jTable2MouseClicked

    private void Filter1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Filter1ActionPerformed
        Filter2.setSelected(false);
        Filter.setSelected(false);
        cbbLoaiSP.setEnabled(false);
        txtTenSP.setEnabled(true);
        if (Filter1.getVerifyInputWhenFocusTarget() == true) {
            Filter1.setSelected(true);
        }              
    }//GEN-LAST:event_Filter1ActionPerformed

    private void Filter2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Filter2ActionPerformed
        Filter1.setSelected(false);
        Filter.setSelected(false);
        cbbLoaiSP.setEnabled(true);
        txtTenSP.setEnabled(false);
        txtTenSP.setText("");
        if (Filter2.getVerifyInputWhenFocusTarget() == true) {
            Filter2.setSelected(true);
        }
        loadDataToTable1(cbbLoaiSP.getSelectedItem().toString());
    }//GEN-LAST:event_Filter2ActionPerformed

    private void txtTenSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenSPActionPerformed
        loadDataToTable2(txtTenSP.getText());
    }//GEN-LAST:event_txtTenSPActionPerformed

    private void cbbLoaiSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbLoaiSPActionPerformed
        loadDataToTable1(cbbLoaiSP.getSelectedItem().toString());
    }//GEN-LAST:event_cbbLoaiSPActionPerformed

    private void FilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FilterActionPerformed
        Filter1.setSelected(false);
        Filter2.setSelected(false);
        txtTenSP.setEnabled(false);
        txtTenSP.setText("");
        cbbLoaiSP.setEnabled(false);
        if (Filter.getVerifyInputWhenFocusTarget() == true) {
            Filter.setSelected(true);
        }
        loadDataToTable();
    }//GEN-LAST:event_FilterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Filter;
    private javax.swing.JRadioButton Filter1;
    private javax.swing.JRadioButton Filter2;
    private javax.swing.JScrollPane JScrollpane1;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbbLoaiSP;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField txtTenSP;
    // End of variables declaration//GEN-END:variables
}
