/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import dao.HoaDonDao;
import dao.SanPhamDao;
import dao.ThongTinHoaDonDao;
import helper.MessageDialogHelper;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.table.DefaultTableModel;
import model.HoaDon;
import model.SanPham;
import model.ThongTinHoaDon;

/**
 *
 * @author nhokk
 */
public class NhanVien_HoaDon extends javax.swing.JPanel {

    /**
     * Creates new form NhanVien_QLHV
     */
    private DefaultTableModel tableModel;
    private DefaultTableModel tableModeltthd;
    private NhanVienMainForm parentForm;
    private HoaDon hd;
    private ThongTinHoaDon tthd;

    public NhanVien_HoaDon() {
        initComponents();

        initTable();
        loadDataToTable();

    }

    private void initTable() {
        tableModel = new DefaultTableModel();
        tableModel.setColumnIdentifiers(new String[]{"Mã hóa đơn", "Mã khách hàng", "Ngày hóa đơn", "Trạng thái"});
        jTable2.setModel(tableModel);
    }

    private void initTableTTHD() {
        tableModeltthd = new DefaultTableModel();
        tableModeltthd.setColumnIdentifiers(new String[]{"Tên sản phẩm", "Số lượng", "Đơn giá"});
        jTable3.setModel(tableModeltthd);
    }

    private void loadDataToTableTTHD(String MaHD) {
        try {
            ThongTinHoaDonDao dao = new ThongTinHoaDonDao();
            List<ThongTinHoaDon> list = dao.findByMaHD(MaHD);
            tableModeltthd.setRowCount(0);
            int TongTien = 0;
            for (ThongTinHoaDon it : list) {
                SanPhamDao dao1 = new SanPhamDao();
                SanPham SP = dao1.findById(it.getMaSP());
                TongTien += SP.getDonGia() * it.getSoLuong();
                tableModeltthd.addRow(new Object[]{
                    SP.getTen(), it.getSoLuong(), SP.getDonGia()
                });
                tableModeltthd.fireTableDataChanged();
            }
            tableModeltthd.addRow(new Object[]{
                "Tổng tiền:", "", TongTien
            });
            tableModeltthd.fireTableDataChanged();
        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(parentForm, e.getMessage(), "Loi");
        }
    }

    private void loadDataToTable() {
        try {
            HoaDonDao dao = new HoaDonDao();
            List<HoaDon> list = dao.findAll();
            tableModel.setRowCount(0);
            for (HoaDon it : list) {
                tableModel.addRow(new Object[]{
                    it.getMaHD(), it.getTaiKhoanKH(), it.getNgayHoaDon(), it.getTrangThai()
                });
                tableModel.fireTableDataChanged();
            }
        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(parentForm, e.getMessage(), "Loi");
        }
    }

    private void loadDataToTable1(String MaHD) {
        try {
            HoaDonDao dao = new HoaDonDao();
            List<HoaDon> list = dao.findByMaHD(MaHD);
            tableModel.setRowCount(0);
            for (HoaDon it : list) {
                tableModel.addRow(new Object[]{
                    it.getMaHD(), it.getTaiKhoanKH(), it.getNgayHoaDon(), it.getTrangThai()
                });
                tableModel.fireTableDataChanged();
            }
        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(parentForm, e.getMessage(), "Loi");
        }
    }

    private void loadDataToTable2(String taikhoanKH) {
        try {
            HoaDonDao dao = new HoaDonDao();
            List<HoaDon> list = dao.findByMaKH(taikhoanKH);
            tableModel.setRowCount(0);
            for (HoaDon it : list) {
                tableModel.addRow(new Object[]{
                    it.getMaHD(), it.getTaiKhoanKH(), it.getNgayHoaDon(), it.getTrangThai()
                });
                tableModel.fireTableDataChanged();
            }
        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(parentForm, e.getMessage(), "Loi");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnXoa1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Filter1 = new javax.swing.JRadioButton();
        Filter2 = new javax.swing.JRadioButton();
        txtMaHD = new javax.swing.JTextField();
        Filter = new javax.swing.JRadioButton();
        txtMaKH = new javax.swing.JTextField();
        JScrollpane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        JScrollpane2 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        btnThem1 = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnThem2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1280, 700));

        btnThem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Sign_Add_Icon_16.png"))); // NOI18N
        btnThem.setText("Thêm hóa đơn");
        btnThem.setBorder(null);
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnRefresh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Refresh-icon (1).png"))); // NOI18N
        btnRefresh.setText("Cập nhật");
        btnRefresh.setBorder(null);
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnXoa1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnXoa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Actions-edit-delete-icon-16.png"))); // NOI18N
        btnXoa1.setText("Xóa");
        btnXoa1.setBorder(null);
        btnXoa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoa1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Danh sách sản phẩm");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(300, Short.MAX_VALUE)
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnXoa1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(340, 340, 340)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnXoa1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        Filter1.setText("Tìm kiếm theo mã hóa đơn");
        Filter1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Filter1ActionPerformed(evt);
            }
        });

        Filter2.setText("Tìm kiếm theo mã khách hàng");
        Filter2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Filter2ActionPerformed(evt);
            }
        });

        txtMaHD.setEnabled(false);
        txtMaHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaHDActionPerformed(evt);
            }
        });

        Filter.setSelected(true);
        Filter.setText("Tìm kiếm tất cả sản phẩm");
        Filter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FilterActionPerformed(evt);
            }
        });

        txtMaKH.setEnabled(false);
        txtMaKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaKHActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMaHD, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Filter2)
                            .addComponent(Filter1)
                            .addComponent(Filter))
                        .addGap(0, 104, Short.MAX_VALUE))
                    .addComponent(txtMaKH, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(Filter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Filter1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtMaHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Filter2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(506, Short.MAX_VALUE))
        );

        JScrollpane1.setBackground(new java.awt.Color(255, 255, 255));
        JScrollpane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JScrollpane1MouseClicked(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A"},
                {"N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A"},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Tai Khoan", "Ho va ten", "Gioi Tinh", "Ngay Sinh", "Dia Chi", "Email", "SDT", "Trinh Do"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        }
    );
    jTable2.setGridColor(new java.awt.Color(0, 0, 0));
    jTable2.setRowHeight(30);
    jTable2.setShowGrid(true);
    jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jTable2MouseClicked(evt);
        }
    });
    JScrollpane1.setViewportView(jTable2);

    JScrollpane2.setBackground(new java.awt.Color(255, 255, 255));
    JScrollpane2.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            JScrollpane2MouseClicked(evt);
        }
    });

    jTable3.setGridColor(new java.awt.Color(0, 0, 0));
    jTable3.setRowHeight(30);
    jTable3.setShowGrid(true);
    jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jTable3MouseClicked(evt);
        }
    });
    JScrollpane2.setViewportView(jTable3);

    btnThem1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    btnThem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Sign_Add_Icon_16.png"))); // NOI18N
    btnThem1.setText("Sửa số lượng");
    btnThem1.setBorder(null);
    btnThem1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnThem1ActionPerformed(evt);
        }
    });

    btnXoa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Actions-edit-delete-icon-16.png"))); // NOI18N
    btnXoa.setText("Xóa");
    btnXoa.setBorder(null);
    btnXoa.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnXoaActionPerformed(evt);
        }
    });

    btnThem2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    btnThem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Sign_Add_Icon_16.png"))); // NOI18N
    btnThem2.setText("Thêm sản phẩm");
    btnThem2.setBorder(null);
    btnThem2.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnThem2ActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGroup(layout.createSequentialGroup()
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, 0)
            .addComponent(JScrollpane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(btnThem2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(btnThem1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(JScrollpane2, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(JScrollpane1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createSequentialGroup()
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnThem2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnThem1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(JScrollpane2, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE))))
    );
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        ThemHoaDon themHD = new ThemHoaDon();
        themHD.setVisible(true);
        themHD.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        XoaTTHD Xoatthd = new XoaTTHD(tthd);
        Xoatthd.setVisible(true);
        Xoatthd.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        Filter1.setSelected(false);
        Filter2.setSelected(false);
        txtMaHD.setEnabled(false);
        txtMaHD.setText("");
        txtMaKH.setEnabled(false);
        txtMaKH.setText("");
        if (Filter.getVerifyInputWhenFocusTarget() == true) {
            Filter.setSelected(true);
        }
        loadDataToTable();;
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void JScrollpane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JScrollpane1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_JScrollpane1MouseClicked

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        try {
            int row = jTable2.getSelectedRow();

            if (row >= 0) {
                String id = (String) jTable2.getValueAt(row, 0);
                HoaDonDao dao = new HoaDonDao();
                hd = dao.findById(id);
                initTableTTHD();
                loadDataToTableTTHD(hd.getMaHD());
            }

            if (hd != null) {

            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jTable2MouseClicked

    private void Filter1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Filter1ActionPerformed
        Filter2.setSelected(false);
        Filter.setSelected(false);
        txtMaHD.setEnabled(true);
        txtMaKH.setEnabled(false);
        txtMaKH.setText("");
        if (Filter1.getVerifyInputWhenFocusTarget() == true) {
            Filter1.setSelected(true);
        }
    }//GEN-LAST:event_Filter1ActionPerformed

    private void Filter2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Filter2ActionPerformed
        Filter1.setSelected(false);
        Filter.setSelected(false);
        txtMaKH.setEnabled(true);
        txtMaHD.setEnabled(false);
        txtMaHD.setText("");
        if (Filter2.getVerifyInputWhenFocusTarget() == true) {
            Filter2.setSelected(true);
        }
    }//GEN-LAST:event_Filter2ActionPerformed

    private void txtMaHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaHDActionPerformed
        loadDataToTable1(txtMaHD.getText());
    }//GEN-LAST:event_txtMaHDActionPerformed

    private void FilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FilterActionPerformed
        Filter1.setSelected(false);
        Filter2.setSelected(false);
        txtMaHD.setEnabled(false);
        txtMaHD.setText("");
        txtMaKH.setEnabled(false);
        txtMaKH.setText("");
        if (Filter.getVerifyInputWhenFocusTarget() == true) {
            Filter.setSelected(true);
        }
        loadDataToTable();;
    }//GEN-LAST:event_FilterActionPerformed

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
        try {
            int row = jTable3.getSelectedRow();

            if (row >= 0) {
                String TenSP = (String) jTable3.getValueAt(row, 0);
                ThongTinHoaDonDao dao = new ThongTinHoaDonDao();
                SanPhamDao dao1 = new SanPhamDao();
                String MaSP = dao1.findMaSPByName(TenSP);
                tthd = dao.findByID(MaSP, hd.getMaHD());
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jTable3MouseClicked

    private void JScrollpane2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JScrollpane2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_JScrollpane2MouseClicked

    private void txtMaKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaKHActionPerformed
        loadDataToTable2(txtMaKH.getText());
    }//GEN-LAST:event_txtMaKHActionPerformed

    private void btnThem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThem1ActionPerformed

    private void btnXoa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoa1ActionPerformed
        XoaHoaDon XoaHD = new XoaHoaDon(hd);
        XoaHD.setVisible(true);
        XoaHD.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnXoa1ActionPerformed

    private void btnThem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThem2ActionPerformed
        ThemTTHD ThemTTHD = new ThemTTHD(hd.getMaHD());
        ThemTTHD.setVisible(true);
        ThemTTHD.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnThem2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Filter;
    private javax.swing.JRadioButton Filter1;
    private javax.swing.JRadioButton Filter2;
    private javax.swing.JScrollPane JScrollpane1;
    private javax.swing.JScrollPane JScrollpane2;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThem1;
    private javax.swing.JButton btnThem2;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXoa1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField txtMaHD;
    private javax.swing.JTextField txtMaKH;
    // End of variables declaration//GEN-END:variables
}
